<a href="https://colab.research.google.com/github/nakib103/tensorflow/blob/master/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.2.0


In [ ]:
# tensors are immutable multi-dimentional array with uniform dtypes
help(tf.dtypes.DType)

In [ ]:
# different rank of tensors
print(tf.constant(0))
print(tf.constant([1., 2., 3.]))
print(tf.constant([[1., 2.],
                   [3., 4.]]))
print(tf.constant([[[1., 2.],
                   [3., 4.]],
                  
                  [[6., 7.],
                   [8., 9.]]]))

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[[1. 2.]
  [3. 4.]]

 [[6. 7.]
  [8. 9.]]], shape=(2, 2, 2), dtype=float32)


In [ ]:
# converting a tensor to numpy array
a = tf.constant([[1., 2.],
                 [3., 4.]])
b = np.array(a)
print(type(b), b)

c = a.numpy()
print(type(c), c)

<class 'numpy.ndarray'> [[1. 2.]
 [3. 4.]]
<class 'numpy.ndarray'> [[1. 2.]
 [3. 4.]]


In [ ]:
# tensor dtype can be string, complex number etc. also
tf.constant("hello")

<tf.Tensor: shape=(), dtype=string, numpy=b'1+i5'>

In [ ]:
# tensor operations: addition, element-wise multiplication, matrix multiplication
a = tf.constant([[1., 3.],
                 [4., 2.]])

b = tf.constant([[5., 2.],
                 [8., 3.]])

print(tf.math.add(a, b))
print(tf.multiply(a, b))
print(tf.matmul(a, b))

tf.Tensor(
[[ 6.  5.]
 [12.  5.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 5.  6.]
 [32.  6.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[29. 11.]
 [36. 14.]], shape=(2, 2), dtype=float32)


In [ ]:
# some other operations
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])
print(tf.reduce_max(c))
print(tf.argmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)


In [ ]:
# indexing same as python

c = tf.constant([1., 3., 7., 10.])

# indexing with scalar removes dimention
print(c[0].numpy())

# indexing with : removes dimention
print(c[0:1,].numpy())

1.0
[1.]


In [ ]:
# The tf.reshape operation is fast and cheap as the underlying data does not need to be duplicated.
c = tf.constant([[1., 5.],
                 [4., 9.]])
d = tf.reshape(c, [1, 4])
print(d)

tf.Tensor([[1. 5. 4. 9.]], shape=(1, 4), dtype=float32)
